# 워크플로우의 이름을 지정합니다. GitHub Actions 탭에 이 이름이 표시됩니다.
name: Deploy to Self-Hosted Server

# 워크플로우가 실행될 조건을 지정합니다.
on:
  push:
    branches:
      - master # 'main' 브랜치에 코드가 푸시될 때 워크플로우를 실행합니다.

# 워크플로우에서 실행될 작업(job)들을 정의합니다.
jobs:
  # 'deploy'라는 이름의 작업을 정의합니다.
  deploy:
    name: Deploy
    # 이 작업이 실행될 러너를 지정합니다. 'self-hosted'로 설정합니다.
    runs-on: self-hosted

    # 작업 내에서 실행될 단계(step)들을 정의합니다.
    steps:
      # 1. 코드 체크아웃
      # actions/checkout 액션을 사용하여 리포지토리의 코드를 러너에 체크아웃합니다.
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 배포 스크립트 실행
      # 프로젝트에 포함된 deploy.sh 스크립트를 실행합니다.
      - name: Run deployment script
        run: ./deploy.sh